---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: kube-prometheus-stack-secrets
  namespace: monitoring
spec:
  suspend: false
  secretTemplates:
    - name: pushover-token
      stringData:
        alertmanager-pushover-token: ENC[AES256_GCM,data:FtSfrQUTkziNfa/tO9S7MoWKT8rm5z4t/gQqNnfK,iv:eaNDTafG/EWe/3tjrk8HeQzovz4I0KRK3cVMLuz80/U=,tag:v6QqZeaE3h9vhYHUeUctTA==,type:str]
        pushover-user-key: ENC[AES256_GCM,data:Lhd0ANOjzhtMr5eBwKKHQaNMioqCSCzYKCnvz0yw,iv:hGZv3Ftv3d0WZ9l1Jq0i82WrAj453QftLx/3GKy00T4=,tag:DEvye5jcELeVI1wso2m9jQ==,type:str]
sops:
  age:
    - recipient: age1haxzj5xhxtpag457wwykd4alk7x0cfdzc0gcfgltlvuh7zfywveqz53gjl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsOUNvQzdSbEszUUhRV0ti
        NnNnajdUdDdLOFI1eGhtd1c4RGdnZVp5ZHdvCmt3UU9iNHBmS3hWSk40Zmlkektu
        QmdQVzRMYTF4TGFacDU3bXk4dFFmMzAKLS0tIHRCbDFhZjJsSVpjZS9Lb1Z3d25i
        eEJILzNHa2JocGdEZm5Tc2laSTdwV00KLRSXnk4YSvksFET4UAA/xx7tpjdgA8ur
        /GuJPhyEiX3u1nBbdv9csBMffMk5a026wKL8A/J4bpJ9mgtO8HJTtA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age10vvdtwte8a0pr2ffuu4r0ln7584q9dst7mkrn22lwkp6amsqm4us68tn0s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdDFtYkF0YnRQMFJ6cXk3
        KzdjSXpoaHF0QWxJbXdvRUw0dDFsUUl6RzJZCkZHTW96R0gzQVB0NG1ieldubHBC
        YWtFbG1McmI3UnZXWTMyajZhRmRGRDQKLS0tIEV4US9JN2g0b2FDMytJMGxPc251
        bFlpWXFwQ255UEhheWQrTlViejVRK3cKS7vyIkZ+35E/HTw/GS1Qd4B30ZCzn9Kb
        mLW5rp+poiiWBSleitBrFwvBEbC3FqvzFaPIxxGfLyaGByBwQmop6A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-07T15:36:53Z"
  mac: ENC[AES256_GCM,data:3gX0oB7f3J6vmHEbQKy+mgNC1pIzOIwFkEQnOw1do/4ANxPZlsz/GMcYcwn6rGi4olq0JpU8JYYhCgymaNoJgZ4HUmt1qIqGjauzmN6YkuKBu8biWikDxsrBKm7XRe1v6a9agsKjkfWbf2T4O3wbrQ2x/EszbQvmJyCmYRCF0iA=,iv:3k8Edjmt3Qt5j64DEq0noXL4lMM8GHWCipQn78kOFIo=,tag:OHg5uITYE001sjgUeOWjEw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
