---
deploymentStrategy:
  type: Recreate
persistence:
  enabled: false
envValueFrom:
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
    secretKeyRef:
      name: grafana-oauth
      key: client-secret
env:
  GF_DATE_FORMATS_USE_BROWSER_LOCALE: true
  GF_EXPLORE_ENABLED: true
grafana.ini:
  analytics:
    check_for_updates: false
    check_for_plugin_updates: false
    reporting_enabled: false
  security:
    disable_initial_admin_creation: true
  server:
    root_url: https://grafana.maddin.dev
    cookie_samesite: strict
    cookie_secure: true
  auth:
    disable_login_form: true
    oauth_auto_login: false
    hide_signup_menu: true
  auth.generic_oauth:
    enabled: true
    client_id: grafana
    name: Keycloak
    allow_sign_up: true
    scopes: "openid email profile offline_access roles"
    email_attribute_path: email
    login_attribute_path: username
    name_attribute_path: full_name
    auth_url: https://keycloak.maddin.dev/auth/realms/cluster/protocol/openid-connect/auth
    token_url: https://keycloak.maddin.dev/auth/realms/cluster/protocol/openid-connect/token
    api_url: https://keycloak.maddin.dev/auth/realms/cluster/protocol/openid-connect/userinfo
    role_attribute_path: >-
      contains(grafana_roles[*], 'admin') && 'Admin' ||  contains(grafana_roles[*], 'editor') && 'Editor'
      || contains(grafana_roles[*], 'viewer') && 'Viewer'
    role_attribute_strict: true
    use_refresh_token: true
  news:
    news_feed_enabled: false
datasources:
  datasources.yaml:
    apiVersion: 1
    deleteDatasources:
      - {name: Alertmanager, orgId: 1}
      - {name: Prometheus, orgId: 1}
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        access: proxy
        url: http://prometheus-operated.monitoring.svc.cluster.local:9090
      - name: Alertmanager
        type: alertmanager
        uid: alertmanager
        access: proxy
        url: http://alertmanager-operated.monitoring.svc.cluster.local:9093
        jsonData:
          implementation: prometheus
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
sidecar:
  dashboards:
    enabled: true
    searchNamespace: ALL
    label: grafana_dashboard
    folderAnnotation: grafana_folder
    provider:
      disableDelete: false
      foldersFromFilesStructure: true
  datasources:
    enabled: true
    searchNamespace: ALL
    labelValue: ""
plugins:
  - grafana-clock-panel
  - grafana-piechart-panel
  - grafana-worldmap-panel
serviceMonitor:
  enabled: true
ingress:
  enabled: false
testFramework:
  enabled: false
dashboards:
  default:
    ceph-cluster:
      gnetId: 2842
      revision: 18
      datasource: Prometheus
    ceph-osd:
      gnetId: 5336
      revision: 9
      datasource: Prometheus
    ceph-pools:
      gnetId: 5342
      revision: 9
      datasource: Prometheus
    kubernetes-api-server:
      gnetId: 15761
      revision: 18
      datasource: Prometheus
    kubernetes-coredns:
      gnetId: 15762
      revision: 19
      datasource: Prometheus
    kubernetes-global:
      gnetId: 15757
      revision: 42
      datasource: Prometheus
    kubernetes-namespaces:
      gnetId: 15758
      revision: 41
      datasource: Prometheus
    kubernetes-nodes:
      gnetId: 15759
      revision: 32
      datasource: Prometheus
    kubernetes-pods:
      gnetId: 15760
      revision: 34
      datasource: Prometheus
    node-exporter-full:
      gnetId: 1860
      revision: 37
      datasource: Prometheus
    prometheus:
      gnetId: 19105
      revision: 6
      datasource: Prometheus
    cloudnative-pg:
      gnetId: 20417
      revision: 3
      datasource: Prometheus
