---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: grafana-secrets
  namespace: monitoring
spec:
  suspend: false
  secretTemplates:
    - name: grafana-oauth
      stringData:
        client-secret: ENC[AES256_GCM,data:+PlwMPPX9St8kdUod+WnwFHmVif1mx0X/g4yyFdmqlk=,iv:3Puu5MOk0Ci9M/bi6ki88G4x/80CECym8VdJ+HQd0wQ=,tag:KXBIUEU0oSHStgUAeG971w==,type:str]
sops:
  age:
    - recipient: age1haxzj5xhxtpag457wwykd4alk7x0cfdzc0gcfgltlvuh7zfywveqz53gjl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxd1lSbXB2QzFhM3g2N2gr
        QWZVZDRDRHN1dWZtczdhdjczK0dRSm92ZHc4CjllY2Z3eUtNYnJ6K2JTc21jN0R2
        OTRMM0JEUmlmTHZtbWhWeUNYa3YzNTAKLS0tIE94TVd4bW0rZWNBTVVhQjVKREUx
        V0ROVldtaUpqODFwY1RWc3pXdFhjY2cKEc7SApAFI9uN7g8WhYVxsZUeBUSaU4Cg
        gfUOdErrtqr17TGPcQqGqw8NOlSnK4wB0ZDjOeCo6U+MPPZ2VjqFCQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age10vvdtwte8a0pr2ffuu4r0ln7584q9dst7mkrn22lwkp6amsqm4us68tn0s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlejBIZU9zVi95QVkxZkRQ
        TnEvT3M2Z2VHL3NsdzlUWmRWTGZsQUx3VkFzCjZmTlpQekUvUG5ZQ3g0bWxjM0Ux
        ejhrdU9rNVE5MmN4ZEhpTU9QaXlEVVEKLS0tIEV1bVRZempOaEVsb2p0RXE0M2lp
        ckI0UE9mQ0lrc1AwNW9ubHQzZFo4WlkKgztbbhxtHC3TvGXGEn714yZf1MOTRXwf
        GzZLkix/LbwzirX3p886zC9XOy7TmNWsCGe+ZLQjLceaL7D7VP91xQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-16T14:31:21Z"
  mac: ENC[AES256_GCM,data:r8+i4SlwETlIb0FFF/9xwmkohqcdQjBUs0H2GKMeQsFCzjRE3GwKi9lpj3KJLqRR/o3OyBrgMRo5BF/8TNctmZTLETlxf8PBi5iEz4A/0M0KDNjELbAT36mict+VlH1FPWsqOcZhTdF+1b0eT1t6Y3baupaRqn4tpdCxDDBFbf0=,iv:Ng64W1M8omL4rRAx8MJNtaPJuHfaqJgi+gv5BDgfbbs=,tag:bEzMRYUBYucLeX7wM67zJg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
