---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  labels:
    app-type: monitoring
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 9.3.2
      helm:
        valueFiles:
          - $app/apps/grafana/values.yaml
    - repoURL: https://github.com/giraffacorp/k8s_monitoring.git
      targetRevision: HEAD
      ref: app
      path: apps/grafana
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m
        factor: 2
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ForceConflicts=true
