---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  labels:
    app-type: monitoring
spec:
  project: default
  sources:
    - repoURL: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
      chart: kube-prometheus-stack
      targetRevision: 75.7.0
      helm:
        valueFiles:
          - $app/apps/kube-prometheus-stack/values.yaml
    - repoURL: https://github.com/giraffacorp/k8s_monitoring.git
      targetRevision: HEAD
      ref: app
      path: apps/kube-prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m
        factor: 2
    syncOptions:
      - CreateNamespace=true
